# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Mule Migration Assistant Build

on:
  push:
    branches: [ master, chore/mig-cost-win ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk: [1.8, 1.11, 1.17] # LTS versions

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v10
      with:
        repositories: '[{ "id": "mulesoft-public", "url": "https://repository.mulesoft.org/nexus/content/repositories/public" },
                        { "id": "mule-releases", "url": "https://repository.mulesoft.org/releases" }]'

    - name: log-settings
      run: cat \/home\/runner\/.m2\/settings.xml

    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}

    - name: mvn-version
      run: mvn --version

    - name: Build with Maven
      run: mvn --settings /home/runner/.m2/settings.xml  clean install --file pom.xml

  build-windows:

    runs-on: windows-latest

    strategy:
      matrix:
        jdk: [1.8, 1.11, 1.17] # LTS versions

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v10
      with:
        repositories: '[{ "id": "mulesoft-public", "url": "https://repository.mulesoft.org/nexus/content/repositories/public" },
                        { "id": "mule-releases", "url": "https://repository.mulesoft.org/releases" }]'

    - name: log-settings
      run: cat C:\Users\runneradmin\.m2\settings.xml

    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}

    - name: mvn-version
      run: mvn --version

    - name: Build with Maven
      run: mvn --settings C:\Users\runneradmin\.m2\settings.xml clean install --file pom.xml
